const PROJECTS_DATA = [
    {
        'id': 1,
        'title': 'FIND',
        'description': 'Designing and planning personal project that is housing service for people. utilizing ReactJS, ContextAPI, Javascript, Mongodb and Firebase',
        'thumbnail': '/images/thumb-1.png',
        'imgUrl' : '/images/main-1.png',
        'projectImg01' : '/images/content1-img-1.jpg',
        'projectImg02' : '/images/content1-img-2.jpg',
        'projectImg03' : '/images/content1-img-3.jpg',
        'projectImg04' : '/images/content1-img-4.png',
        'bgColor': '#DC3545',
        'url': 'find',
        'viewLink': 'https://find-house-van.herokuapp.com',
        'appleStore': '',
        'googlePlay': '',
        'type': 'WEB',
        'develop': 'Web Development',
        'project': 'Personal Project',
        'useProgram':'HTML5, CSS, ReactJS, ContextAPI, Javascript, Mongodb, Firebase',
        'date': 'October 1, 2019'
    },
    {
        'id': 2,
        'title': 'METAL REVISION',
        'description': 'Developed a company website for factory, using HTML5, CSS, BootStrap, jQuery, javascript and WordPress Communicated with designers and project managers for project milestones Tested functionalities of final product',
        'thumbnail': '/images/thumb-2.png',
        'imgUrl' : '/images/main-2.png',
        'projectImg01' : '/images/content2-img-1.jpg',
        'projectImg02' : '/images/content2-img-2.jpg',
        'projectImg03' : '/images/content2-img-3.jpg',
        'projectImg04' : '/images/content2-img-4.png',
        'bgColor': '#1F2E96',
        'url': 'metal-revision',
        'viewLink': 'http://www.metal-rev.co.jp/',
        'appleStore': '',
        'googlePlay': '',
        'type': 'WEB',
        'develop': 'Web Development',
        'project': 'Freelance',
        'useProgram':'HTML5, CSS, jQuery, WordPress',
        'date': 'February 1, 2019'
    },
    {
        'id': 3,
        'title': 'SOCCER MEET',
        'description': 'Designing and planning project goals Designing and creating an interface for soccer teams utilizing ReactJS, Firebase, Javascript. Using XD to create design.',
        'thumbnail': '/images/thumb-3.png',
        'imgUrl' : '/images/main-3.png',
        'projectImg01' : '/images/content3-img-1.jpg',
        'projectImg02' : '/images/content3-img-2.jpg',
        'projectImg03' : '/images/content3-img-3.jpg',
        'bgColor': '#00807C',
        'url': 'soccer-meet',
        'appleStore': '',
        'googlePlay': '',
        'type': 'Mobile',
        'develop': 'Mobile Development',
        'project': 'Personal Project',
        'useProgram':'React Native, Firebase',
        'date': 'July 1, 2019'
    }
]

export default PROJECTS_DATA;